services:
  - type: web
    name: new-ikuuni-fms
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        value: https://lmhapnpqdxzgrsoupklq.supabase.co
      - key: SUPABASE_ANON_KEY
        value: sb_publishable_72jelmMtrLfKl592C_VhuA_r0So5Mcx
      - key: PORT
        value: 10000
